name: Test Action

on: 
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 21f2001412@ds.study.iitm.ac.in
        run: echo "Hello, world!"
